# Source language and JDK version to use.
language: java
jdk: oraclejdk7

# Get files for use with build, namely the custom Maven settings.xml.
before_install:
  - "git clone https://github.com/Q0rDev/travis-ci-resources.git target/travis"
  - "chmod +x target/travis/build.sh"
  - "gem install travis-artifacts"

# Compile and package JAR and set build properties.
install: ./target/travis/build.sh
script: true

# Push artifacts to AWS.
after_success:
  - travis-artifacts upload --path target/*.jar --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER

notifications:
  # Disable build status email notifications, until the issue with forks is fixed.
  email: false
  webhooks:
    # Send build information and status to Notifico.
    - http://n.tkte.ch/h/2332/WVYtfpROKoor-8Nrm5qljibz

env:
  global:
    - secure: "gmA1SJmEmRjnPhGvdAHQnhQRpd0ijQEUXwJio3l82oS+T/VEJVf4HW1eqRGt8U9ruVqc8cQc4wFUNBZ0JMBWbD3JnqcgWkPFlsx4ylzwxp2r54IYKEfGjaDbnGOcDMCgIxqvPSxVBIa4GfUOTFSr+hKcAA9vJt91DcG57dY03PI="
    - secure: "MDiFJgtSEfJDgRnaOfihj1UCOXhF2Blvcws6OwERwXibWXnjNa3TgTTpXg5ecEQio3dUMTPYaer9E9V1YmzBCi3CAhgW1fp007GD0qNkAbCPuNVKeLADws4zULSPtx78rzu4rT2yf3Td0didOGkd/+1bNKvNMoIXipMoXHD2wrE="
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=q0r-artifacts"
    - secure: "c/HdYCPLTRlzkDgfCqEJgcuMe8b4AfcfDpgkdw6/ht+hTbgpFLL4GKjQ3bwIg2DhE9KwI1y+j6U8fuiGBGGWIHSEEOiSyjFoeB9YCcffA2Lohihjbbeq3ycz0w4k1VyeBhNPenycu8+05dIhX2dz+148LxGZSOIh6WhYlU7ruGY="
    - secure: "GziPztDs5ZAqrX2QNdJeC6aEVoxG0fJjSbuIyofXCYFccYnH8vXCFuGxoShDHeg3JevSdwQB0U9x8ss6h7uAx59fkJyRp6MYbQbRmRrY8jbcHZuREDIQhdQdsez5yeVN2cZ2PmER2YYYCLTJHzuAjFJb19HTqco7V8Zrj2up3vo="