name: MChannels
main: com.miraclem4n.mchannels.MChannels
version: ${version}-${build.number}
author: MiracleM4n
authors: [MiracleM4n]
website: http://mdev.in/
softdepend: [mChatSuite, MChat]
description: MChat's Channel Implementation
commands:
    mchannel:
        aliases: [mchann, mchan]
permissions:
    mchannel.*:
        default: op
        description: Allows full use of MChannels.
        children:
            mchannel.reload: true
    mchannel.reload:
        default: false
        description: Allow usage of /mchannel reload command.
